apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pql920a40-dotnet-basic 
  janus-idp.io/tekton: pql920a40-dotnet-basic
  backstage.io/kubernetes-id: pql920a40-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pql920a40-dotnet-basic
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  